---
# Source: airflow/templates/pvc-logs.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs
  labels:
    app: airflow
    chart: airflow-8.7.1
    release: airflow
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "5Gi"
  storageClassName: "default"
