---
# Source: airflow/templates/pgbouncer/pgbouncer-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: airflow-pgbouncer
  labels:
    app: airflow
    component: pgbouncer
    chart: airflow-8.7.1
    release: airflow
    heritage: Helm
spec:
  type: ClusterIP
  selector:
    app: airflow
    component: pgbouncer
    release: airflow
  ports:
    - name: pgbouncer
      protocol: TCP
      port: 6432
