---
# Source: airflow/templates/sync/sync-users-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-sync-users
  labels:
    app: airflow
    component: sync-users
    chart: airflow-8.7.1
    release: airflow
    heritage: Helm
spec:
  replicas: 1
  strategy:
    ## only 1 replica should run at a time
    type: Recreate
  selector:
    matchLabels:
      app: airflow
      component: sync-users
      release: airflow
  template:
    metadata:
      annotations:
        checksum/secret-config-envs: 417fb1258803452f520a433ffcbcc81cc94c440daca553a1bb2be210ea784716
        checksum/secret-local-settings: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        checksum/sync-users-script: 08d39f38a4119e738bb6631335c8d7135f986300b8547375511a39948a26b223
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: airflow
        component: sync-users
        release: airflow
    spec:
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      securityContext:
        fsGroup: 0
      serviceAccountName: airflow
      initContainers:
        ## git-sync is included so "airflow plugins" & "python packages" can be stored in the dags repo        
        - name: dags-git-clone
          image: registry.k8s.io/git-sync/git-sync:v3.6.5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65533
            runAsGroup: 65533
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:    
            - secretRef:
                name: airflow-config-envs
          env:
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_ROOT
              value: "/dags"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_REPO
              value: "git@github.com:viniciusdsmello/airflow-k8s-gitsync.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_TIMEOUT
              value: "120"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "0"
            - name: GIT_SYNC_SUBMODULES
              value: "recursive"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: "/etc/git-secret/id_rsa"
            - name: GIT_KNOWN_HOSTS
              value: "false"    
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "0"
          volumeMounts:
            - name: dags-data
              mountPath: /dags
            - name: git-secret
              mountPath: /etc/git-secret/id_rsa
              readOnly: true
              subPath: id_rsa        
        - name: check-db  
          image: viniciusdsmello/airflow-k8s:v1.0.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 50000
            runAsGroup: 0
          envFrom:    
            - secretRef:
                name: airflow-config-envs
          env:    
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "0"
          command:    
            - "/usr/bin/dumb-init"
            - "--"
            - "/entrypoint"
          args:
            - "bash"
            - "-c"
            - "exec timeout 60s airflow db check"
          volumeMounts:    
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: logs-data
              mountPath: /opt/airflow/logs
              subPath:         
        - name: wait-for-db-migrations  
          image: viniciusdsmello/airflow-k8s:v1.0.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 50000
            runAsGroup: 0
          envFrom:    
            - secretRef:
                name: airflow-config-envs
          env:    
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "0"
          command:    
            - "/usr/bin/dumb-init"
            - "--"
            - "/entrypoint"
          args:
            - "bash"
            - "-c"
            - "exec airflow db check-migrations -t 60"
          volumeMounts:    
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: logs-data
              mountPath: /opt/airflow/logs
              subPath: 
      containers:
        - name: sync-airflow-users          
          image: viniciusdsmello/airflow-k8s:v1.0.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 50000
            runAsGroup: 0
          resources:
            {}
          envFrom:            
            - secretRef:
                name: airflow-config-envs
          env:            
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "0"
          command:            
            - "/usr/bin/dumb-init"
            - "--"
            - "/entrypoint"
          args:
            - "python"
            - "-u"
            - "/mnt/scripts/sync_users.py"
          volumeMounts:            
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: logs-data
              mountPath: /opt/airflow/logs
              subPath: 
            - name: scripts
              mountPath: /mnt/scripts
              readOnly: true
        ## git-sync is included so "airflow plugins" & "python packages" can be stored in the dags repo        
        - name: dags-git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65533
            runAsGroup: 65533
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:    
            - secretRef:
                name: airflow-config-envs
          env:
            - name: GIT_SYNC_ROOT
              value: "/dags"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_REPO
              value: "git@github.com:viniciusdsmello/airflow-k8s-gitsync.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_TIMEOUT
              value: "120"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "0"
            - name: GIT_SYNC_SUBMODULES
              value: "recursive"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: "/etc/git-secret/id_rsa"
            - name: GIT_KNOWN_HOSTS
              value: "false"    
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgres
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "0"
          volumeMounts:
            - name: dags-data
              mountPath: /dags
            - name: git-secret
              mountPath: /etc/git-secret/id_rsa
              readOnly: true
              subPath: id_rsa
      volumes:        
        - name: dags-data
          emptyDir: {}
        - name: logs-data
          persistentVolumeClaim:
            claimName: airflow-logs
        - name: git-secret
          secret:
            secretName: airflow-gitsync
            defaultMode: 0644
        - name: scripts
          secret:
            secretName: airflow-sync-users
