---
# Source: airflow/templates/config/secret-config-envs.yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflow-config-envs
  labels:
    app: airflow
    chart: airflow-8.7.1
    release: airflow
    heritage: Helm
## we must use `data` rather than `stringData` (see: https://github.com/helm/helm/issues/10010)
data:
  ## ================
  ## Linux Configs
  ## ================
  TZ: "RXRjL1VUQw=="

  ## ================
  ## Database Configs
  ## ================
  ## database host/port
  DATABASE_HOST: "YWlyZmxvdy1wZ2JvdW5jZXIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA=="
  DATABASE_PORT: "NjQzMg=="

  ## database configs
  DATABASE_DB: "YWlyZmxvdw=="

  ## bash command which echos the URL encoded value of $DATABASE_USER
  DATABASE_USER_CMD: "ZWNobyAiJHtEQVRBQkFTRV9VU0VSfSIgfCBweXRob24zIC1jICJpbXBvcnQgdXJsbGliLnBhcnNlOyBlbmNvZGVkX3VzZXIgPSB1cmxsaWIucGFyc2UucXVvdGUoaW5wdXQoKSk7IHByaW50KGVuY29kZWRfdXNlciki"

  ## bash command which echos the URL encoded value of $DATABASE_PASSWORD
  DATABASE_PASSWORD_CMD: "ZWNobyAiJHtEQVRBQkFTRV9QQVNTV09SRH0iIHwgcHl0aG9uMyAtYyAiaW1wb3J0IHVybGxpYi5wYXJzZTsgZW5jb2RlZF9wYXNzID0gdXJsbGliLnBhcnNlLnF1b3RlKGlucHV0KCkpOyBwcmludChlbmNvZGVkX3Bhc3MpIg=="

  ## bash command which echos the DB connection string in SQLAlchemy format
  DATABASE_SQLALCHEMY_CMD: "ZWNobyAtbiAicG9zdGdyZXNxbCtwc3ljb3BnMjovLyQoZXZhbCAkREFUQUJBU0VfVVNFUl9DTUQpOiQoZXZhbCAkREFUQUJBU0VfUEFTU1dPUkRfQ01EKUAke0RBVEFCQVNFX0hPU1R9OiR7REFUQUJBU0VfUE9SVH0vJHtEQVRBQkFTRV9EQn0i"

  ## bash command which echos the DB connection string in Celery result_backend format
  DATABASE_CELERY_CMD: "ZWNobyAtbiAiZGIrcG9zdGdyZXNxbDovLyQoZXZhbCAkREFUQUJBU0VfVVNFUl9DTUQpOiQoZXZhbCAkREFUQUJBU0VfUEFTU1dPUkRfQ01EKUAke0RBVEFCQVNFX0hPU1R9OiR7REFUQUJBU0VfUE9SVH0vJHtEQVRBQkFTRV9EQn0i"
  ## bash command which echos the DB connection string in `psql` cli format
  ## NOTE: uses `127.0.0.1` as the host because this is only used in the pgbouncer liveness probe
  ##       and minikube does not allow pods to access their own `cluster.local` service so would otherwise fail
  DATABASE_PSQL_CMD: "ZWNobyAtbiAicG9zdGdyZXNxbDovLyQoZXZhbCAkREFUQUJBU0VfVVNFUl9DTUQpOiQoZXZhbCAkREFUQUJBU0VfUEFTU1dPUkRfQ01EKUAxMjcuMC4wLjE6JHtEQVRBQkFTRV9QT1JUfS8ke0RBVEFCQVNFX0RCfSR7REFUQUJBU0VfUFJPUEVSVElFU30i"

  ## ================
  ## Airflow Configs (General)
  ## ================
  AIRFLOW__CORE__DAGS_FOLDER: "L29wdC9haXJmbG93L2RhZ3MvcmVwby9kYWdz"
  AIRFLOW__CORE__EXECUTOR: "S3ViZXJuZXRlc0V4ZWN1dG9y"
  AIRFLOW__WEBSERVER__SECRET_KEY: "YWlyZmxvdy1mZXJuZXQta2V5"
  AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "ODA4MA=="
  ## refresh the dags folder at the same frequency as git-sync
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "NjA="

  ## ================
  ## Airflow Configs (Database)
  ## ================
  
  ## `core.sql_alchemy_conn` moved to `database.sql_alchemy_conn` in airflow 2.3.0
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD: "YmFzaCAtYyAnZXZhbCAiJERBVEFCQVNFX1NRTEFMQ0hFTVlfQ01EIic="

  ## ================
  ## Airflow Configs (Triggerer)
  ## ================
  AIRFLOW__TRIGGERER__DEFAULT_CAPACITY: "MTAwMA=="

  ## ================
  ## Airflow Configs (Logging)
  ## ================
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "L29wdC9haXJmbG93L2xvZ3M="
  AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "L29wdC9haXJmbG93L2xvZ3MvZGFnX3Byb2Nlc3Nvcl9tYW5hZ2VyL2RhZ19wcm9jZXNzb3JfbWFuYWdlci5sb2c="
  AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: "L29wdC9haXJmbG93L2xvZ3Mvc2NoZWR1bGVy"


  ## ================
  ## Airflow Configs (Kubernetes)
  ## ================
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "dmluaWNpdXNkc21lbGxvL2FpcmZsb3ctazhz"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY: "dmluaWNpdXNkc21lbGxvL2FpcmZsb3ctazhz"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "djEuMC4w"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG: "djEuMC4w"
  AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE: "L29wdC9haXJmbG93L3BvZF90ZW1wbGF0ZXMvcG9kX3RlbXBsYXRlLnlhbWw="
  AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE: "L29wdC9haXJmbG93L3BvZF90ZW1wbGF0ZXMvcG9kX3RlbXBsYXRlLnlhbWw="

  ## ================
  ## User Configs
  ## ================
  "AIRFLOW__CORE__LOAD_EXAMPLES": "VHJ1ZQ=="
  "AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS": "VHJ1ZQ=="
  "AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS": "VHJ1ZQ=="
  "AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE": "RmFsc2U="
  "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE": "ZGVmYXVsdA=="
  "AIRFLOW__LOGGING__LOGGING_LEVEL": "SU5GTw=="
  "AIRFLOW__WEBSERVER__BASE_URL": "aHR0cHM6Ly95b3VyLWRvbWFpbi5jb20="
  "AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW": "Z3JpZA=="
  "AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX": "VHJ1ZQ=="
  "AIRFLOW__WEBSERVER__EXPOSE_CONFIG": "VHJ1ZQ=="
  "AIRFLOW__WEBSERVER__INSTANCE_NAME": "QWlyZmxvdyBQcm9kdWN0aW9uIEVudmlyb25tZW50"
  "AIRFLOW__WEBSERVER__PAGE_SIZE": "MjU="
  "AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE": "VHJ1ZQ=="
