---
# Source: airflow/templates/config/configmap-pod-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template
  labels:
    app: airflow
    chart: airflow-8.7.1
    release: airflow
    heritage: Helm
data:
  pod_template.yaml: |-
    
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-name
    spec:
      restartPolicy: Never
      serviceAccountName: airflow
      shareProcessNamespace: false
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      securityContext:
        fsGroup: 0
      initContainers:    
        - name: dags-git-clone
          image: registry.k8s.io/git-sync/git-sync:v3.6.5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65533
            runAsGroup: 65533
          resources:
            null
          envFrom:    
            - secretRef:
                name: airflow-config-envs
          env:
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_ROOT
              value: "/dags"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_REPO
              value: "git@github.com:viniciusdsmello/airflow-k8s-gitsync.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_WAIT
              value: "60"
            - name: GIT_SYNC_TIMEOUT
              value: "120"
            - name: GIT_SYNC_ADD_USER
              value: "true"
            - name: GIT_SYNC_MAX_SYNC_FAILURES
              value: "0"
            - name: GIT_SYNC_SUBMODULES
              value: "recursive"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: "/etc/git-secret/id_rsa"
            - name: GIT_KNOWN_HOSTS
              value: "false"    
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "0"
          volumeMounts:
            - name: dags-data
              mountPath: /dags
            - name: git-secret
              mountPath: /etc/git-secret/id_rsa
              readOnly: true
              subPath: id_rsa
      containers:
        - name: base      
          image: viniciusdsmello/airflow-k8s:v1.0.0
          imagePullPolicy: Always
          securityContext:
            runAsUser: 50000
            runAsGroup: 0
          envFrom:        
            - secretRef:
                name: airflow-config-envs
          env:
            ## KubernetesExecutor Pods use LocalExecutor internally
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor        
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
            - name: CONNECTION_CHECK_MAX_COUNT
              value: "20"
          ports: []
          command: []
          args: []
          volumeMounts:        
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: logs-data
              mountPath: /opt/airflow/logs
              subPath: 
      volumes:    
        - name: dags-data
          emptyDir: {}
        - name: logs-data
          persistentVolumeClaim:
            claimName: airflow-logs
        - name: git-secret
          secret:
            secretName: airflow-gitsync
            defaultMode: 0644
